name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  test_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into Staging Server and Test
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}

      - name: Add Staging Server to Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEV_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run Tests on Staging
        run: ssh -v ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SSH_HOST }} bash /app/deploy.sh rina_deguchi

  deploy_production:
    runs-on: ubuntu-latest
    needs: test_staging
    steps:
      - name: SSH into Production Server and Deploy
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.PRO_SSH_HOST }}
          SSH_PORT: ${{ secrets.PRO_SSH_PORT }}
          SSH_USER: ${{ secrets.PRO_SSH_USER }}
          SSH_KEY: ${{ secrets.PRO_SSHE_SSH_KEY }}

      - name: Add Production Server to Known Hosts
        run: ssh-keyscan -H ${{ secrets.PRO_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run Deployment on Production
        run: ssh ${{ secrets.PRO_SSH_USER }}@${{ secrets.PRO_SSH_HOST }} bash /app/deploy.sh rina_deguchi
